### ISSUE TITLE
Spawn blocking blocking sim runtime

### ISSUE THREAD

**Issue by LucioFranco** [tokio-rs/turmoil#139]
https://github.com/tokio-rs/turmoil/compare/main...lucio/spawn-blocking-bug#diff-ace3e8abab9fb7b84efd253a7cea095084172b5cc3431426e3391305a554b152R46

With this example code its possible to never run the client future as the server one will hang until all spawn blockings complete. The real answer here is to not use threads since this removes determinism. But this is still surprising behavior. The work around is to use another thread provider like a different tokio runtime (where you call spawn_blocking on that) or `std::thread`.

cc @MarinPostma @mcches

**Comment by mcches** [comment]
This is a known issue with a paused runtime where spawn_blocking does not allow time to advance. Since we advance time using a sleep on the LocalSet, things lock up in this scenario.

See: https://github.com/tokio-rs/tokio/pull/5115

We aren't planning to do anything to make this work, rather we'll add tracing events if it occurs in #160.
