### ISSUE TITLE
Infinitely running.

### ISSUE THREAD

**Issue by violin0622** [tokio-rs/turmoil#144]
Hi, I'm not sure it is a bug, but given the code below ( I know it's a misuse of `TcpListener`) , 
the sim runs infinitely, and it is expected to stop within 10 logical seconds, and far shorter real world duration.

Maybe it's make sense to add a new simulator config like `realworld_duration` ?

```rust
#[test]
fn infinite() -> turmoil::Result {
    use std::time::SystemTime;
    use turmoil::{net::TcpListener, Builder};

    let mut sim = Builder::new().epoch(SystemTime::UNIX_EPOCH).build();
    sim.host("s", || async {


        loop {
            TcpListener::bind("0.0.0.0:80").await?;
        }
    });

    sim.run()
}
```

![截屏2023-11-03 18 04 54](https://github.com/tokio-rs/turmoil/assets/6880156/578c4240-549b-47f7-af09-17e1d4ae0ed8)

**Comment by mcches** [comment]
We've talked about adding an external monitor thread that ensures we don't have runaway tests due to infinite blocking logic. If a real duration elapses we could just panic the test.

There is also some fidelity gaps with bind and send where they actually don't every yield. That might also be something worth looking into, but you could still break it with just a simple infinite busy loop.

**Comment by mcches** [comment]
Tracking in #160
